services:
  postgres:
    build:
      context: .
      dockerfile: database.Dockerfile
    container_name: postgres
    environment:
      - DB_USERS=user1,user2
      - db_user1_pw=s1
      - db_user2_pw=s2
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data_17:/var/lib/postgresql/data
    restart: always

volumes:
  pg_data_17:
