services:
  schema-postgres:
    build:
      context: .
      dockerfile: database.Dockerfile
    container_name: postgres
    environment:
      - SCHEMAS_USERS=schema1,schema2
      - db_schema1_pw=s1
      - db_schema2_pw=s2
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data_17:/var/lib/postgresql/data
    restart: always

volumes:
  pg_data_17:
