name: Publish - Postgres Dynamic Schemas

on:
  push:
    branches:
      - main
    paths:
      - src/postgres/**
      - .github/workflows/docker-build-postgres.yml
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - src/postgres/**
      - .github/workflows/docker-build-postgres.yml

jobs:
  compute-version:
    runs-on: ubuntu-latest
    steps:
      - name: Compute Version
        id: compute-version
        uses: Zuricos/gh-actions/compute-version@main
        with:
          prefix: "postgres-v17.5-bookworm"
          paths: "src/postgres .github/workflows/docker-build-postgres.yml"
    outputs:
      prefix: ${{ steps.compute-version.outputs.prefix }}
      version: ${{ steps.compute-version.outputs.version }}
      suffix: ${{ steps.compute-version.outputs.suffix }}
      needsBump: ${{ steps.compute-version.outputs.needs_bump }}
      version_tag: ${{ steps.compute-version.outputs.version_tag }}

  build-and-publish:
    needs: compute-version
    if: ${{ needs.compute-version.outputs.needsBump }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
      attestations: write
    steps:
      - uses: actions/checkout@v4
      - name: Set Container Prefix
        id: set-container-prefix
        run: echo "CONTAINER_PREFIX=v17.5-bookworm" >> $GITHUB_OuTPUTS
      - name: Build and Publish Docker Image
        id: build_and_publish
        uses: Zuricos/gh-actions/docker-build-and-publish@main
        with:
          platforms: linux/amd64
          context:  src
          dockerfile: src/postgres/database.Dockerfile
          image-name: postgres-dynamic-schemas
          version-tag: ${{ steps.set-container-prefix.outputs.CONTAINER_PREFIX }} ${{ needs.compute-version.outputs.version }}${{ needs.compute-version.outputs.suffix }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Tag
        uses: Zuricos/gh-actions/push-tag@main
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          tag: ${{ needs.compute-version.outputs.version_tag }}${{ needs.compute-version.outputs.suffix }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ghcr.io/zuricos/postgres-dynamic-schemas
          subject-digest: ${{ steps.build_and_publish.outputs.image-digest }}
          push-to-registry: true 